targets:
  $default:
    builders:
      freezed:
        options:
          # Generate freezed files in generated/ subfolder
          build_extensions:
            ".dart": [".freezed.dart"]
        generate_for:
          - lib/features/**/models/*.dart
      json_serializable:
        generate_for:
          - lib/features/**/models/*.dart
